version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app-container
  node-app-container:
    image: alexsoto2/myapp
    deploy:
      replicas: 2